/**
 * This class is generated by jOOQ
 */
package io.pturczyk.jooq.domain;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in publib
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>publib.authors_a_id_seq</code>
     */
    public static final Sequence<Long> AUTHORS_A_ID_SEQ = new SequenceImpl<Long>("authors_a_id_seq", Publib.PUBLIB, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>publib.books_b_id_seq</code>
     */
    public static final Sequence<Long> BOOKS_B_ID_SEQ = new SequenceImpl<Long>("books_b_id_seq", Publib.PUBLIB, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
