/**
 * This class is generated by jOOQ
 */
package io.pturczyk.jooq.domain;


import io.pturczyk.jooq.domain.tables.Authors;
import io.pturczyk.jooq.domain.tables.Books;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in publib
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>publib.authors</code>.
     */
    public static final Authors AUTHORS = io.pturczyk.jooq.domain.tables.Authors.AUTHORS;

    /**
     * The table <code>publib.books</code>.
     */
    public static final Books BOOKS = io.pturczyk.jooq.domain.tables.Books.BOOKS;
}
